@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}
# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Kalu Dematto Gastaldelli",
    "email": "example2@example.com",
    "password": "1234567"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "example2@example.com",
    "password": "1234567"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta",
  "content": "Conteudo da Pergunta"
}